### ISSUE TITLE
Is function 'handleSortClick' in use?

### ISSUE THREAD

**Issue by kayazinc** [alyssaq/react-redux-table-example#38]
In NutrientTable.js, there is a function called `handleSortClick()`, where is this function being used?
Please advise, thanks!

**Comment by alyssaq** [comment]
Ah! Its been replaced by the `SortHeaderCell` component. Would you like to send a pull request removing that function?

**Comment by kayazinc** [comment]
First time doing a pull, let me try.

**Comment by kayazinc** [comment]
I tried to push a branch but was denied.
```
$ git push origin pull-remove-unused
remote: Permission to alyssaq/react-redux-table-example.git denied to kayazinc.
fatal: unable to access 'https://github.com/alyssaq/react-redux-table-example.git/': The requested URL returned error: 403
```

Is there any permission you need to allow?

**Comment by kayazinc** [comment]
Done, thank you @alyssaq.

**Comment by alyssaq** [comment]
Thanks! Ive merged your pull request.
